apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-go
  labels:
    app: backend-go
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: backend-go
  template:
    metadata:
      labels:
        app: backend-go
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
              - containerPort: {{ .Values.service.port }}
